local Config = {}

Config.Architect = {
    Name = "Optimized Architect",
    Identifier = "OptimizedArchitect",
    Title = "θptimized Architect",
    Tooltip = "Activate Optimized Architect",
    ButtonName = "Open"
}

Config.Colors = {
    Background = Color3.new(0.145098, 0.164706, 0.227451),
    Sidebar = Color3.new(0.160784, 0.180392, 0.254902),
    Holder = Color3.new(0.168627, 0.192157, 0.266667)
}

Config.Menu = {
    MainPadding = UDim.new(0, 12),
    CornerRadius = UDim.new(0, 8),
    SidebarWidth = 128,
    ArrowPadding = 48,
}

return Config